[package]
name = "tauri-plugin-tun-device"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-tun-device"

[dependencies]
anyhow = "1"
lattis-core = { workspace = true }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
