[workspace]
resolver = "3"
members = ["app", "cli", "core", "netlab"]

[workspace.package]
version = "0.0.1"
authors = ["ImFeH2 <i@feh2.im>"]
edition = "2024"
description = "A connected space where your devices can work together."
readme = "README.md"
repository = "https://github.com/ImFeH2/lattis"
license = "Apache-2.0"

[workspace.dependencies]
lattis-core = { path = "core", version = "0.0.1" }
netlab = { path = "netlab", version = "0.0.1" }
