[workspace]
resolver = "2"
members = ["app", "cli", "core", "net-lab"]

[workspace.package]
version = "0.0.1"
edition = "2024"
authors = ["ImFeH2 <i@feh2.im>"]
description = "A connected space where your devices can work together."
license = "Apache-2.0"
repository = "https://github.com/ImFeH2/lattis"
readme = "README.md"

[workspace.dependencies]
lattis-core = { version = "0.0.1", path = "core" }
net-lab = { version = "0.0.1", path = "net-lab" }
