[workspace]
resolver = "2"
members = [
    "app",
    "core",
    "desktop",
    "mobile",
    "web",
]

[workspace.package]
version = "0.1.2"
edition = "2024"
authors = ["ImFeH2 <i@feh2.im>"]
description = "A connected space where your devices can work together."
license = "Apache-2.0"
repository = "https://github.com/ImFeH2/lattis"
readme = "README.md"

[workspace.dependencies]
dioxus = { version = "0.7.9" }
lattis = { path = "app" }
lattis-core = { path = "core" }
