[application]
name = "Lattis"
tailwind_input = "assets/tailwind.css"
tailwind_output = "assets/app.css"

[bundle]
identifier = "im.feh2.lattis"
publisher = "ImFeH2"
category = "Utility"
short_description = "A connected space where your devices can work together."
long_description = """
Lattis is a connected space where your devices can work together. It brings computers, phones, tablets, and servers into one place, with extensible capabilities for transferring files, syncing folders, browsing files, sharing clipboard content, viewing screens, controlling devices, opening local apps, running automations, and more.
"""
