allow-branch = ["main"]
shared-version = true
dependent-version = "upgrade"
metadata = "optional"

consolidate-commits = true
pre-release-commit-message = "chore: release {{version}}"

tag-name = "v{{version}}"
tag-message = "chore: release {{version}}"
sign-commit = true
sign-tag = true

publish = false
verify = false

push = true
push-remote = "origin"
