[package]
name = "lattis-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "lattis"
path = "src/main.rs"

[dependencies]
lattis-core = { workspace = true }
