[package]
name = "lattis-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
autobins = false

[dependencies]
lattis-core = { workspace = true }

[[bin]]
name = "lattis"
path = "src/main.rs"
