[package]
name = "lattis-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
anyhow = "1"
if-addrs = "0.15"

[dev-dependencies]
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "net",
    "sync",
    "time",
] }
net-topo = { workspace = true }
