[package]
name = "net-lab"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
anyhow = "1"
futures-util = "0.3"
nix = { version = "0.30", default-features = false, features = [
    "sched",
    "mount",
    "fs",
] }
rtnetlink = "0.21"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "net",
    "time",
    "macros",
] }
